### ISSUE TITLE
Decide how breadcrumbs should work

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej.github.io#10]
As pointed out by @hinerm, the current way breadcrumbs are set up may need to be revised. Pending further discussion!

**Comment by hinerm** [comment]
@elevans @ctrueden 
Thoughts:
* The only time breadcrumbs can actually be used right now is navigating from a particular category back to the `Categories` page.
* The `Home` breadcrumb is redundant since there is a `Home` button directly above it
* On the "leaf" non-category pages, it seems reasonable that I might want to see all of the `Categories` tagged on that page

So I'm in favor of:
1. Removing breadcrumbs
1. Adding something like a "view all" button to each individual category page to navigate back to `Categories`
1. Adding a `Categories` box on non-category pages with links to each tagged category.

**Comment by ctrueden** [comment]
We decided to remove the breadcrumbs. They can always be readded later.
