### ISSUE TITLE
Make double-click on code block select all code

### ISSUE THREAD

**Issue by imagejan** [imagej/imagej.github.io#104]
On the old ImageJ wiki, it was possible to select entire code blocks (e.g. in order to copy them) by double-clicking somewhere in the code. It would be nice if that behavior was supported by the new site as well.

**Comment by ctrueden** [comment]
This is possible with code embedded from GitHub. Mouse over the code, and you'll see a Copy button appear on the top right of the code block. If you want to investigate how to add javascript to do this for the [Liquid-based and/or code fenced code blocks](https://imagej.github.io/help/editing/code) as well, by all means, feel free!

**Comment by ehrenfeu** [comment]
I know I am a bit late to the game here, but nevertheless I would like to add my thoughts on this...

Making double-click select a whole code-box is one of my most-hated "features" in e.g. Atlassian Confluence as it is in contrast to basically *any* other behavior when double-clicking on text. In almost any other tool a double click will select the word that is being clicked on, with the option of keeping the mouse button pressed to extend the selection.

This is something I am using a lot and diverting from the common behavior is not very helpful IMHO - actually I have seen a few other people swearing at the computer as well when something like this happened...

Personally, when I'm copy-pasting stuff from a website (as opposed to forking some code through git for example), I'm usually doing this because I want to understand a process and go through it "interactively".

Having an option to copy an entire code block is certainly nice, but killing standard behavior is just creating confusion. I believe the old "tudor" wiki had a copy-button in the title bar of each code block, in my opinion that's a much better solution to the task.

Cheers,
Niko

**Comment by imagejan** [comment]
I see your point, @ehrenfeu. My intent was to enable easy selection of entire code blocks, since that's what users e.g. accessing https://imagej.net/plugins/trackmate/scripting will most likely do. (That code is not hosted on a git repo, and furthermore I don't assume readers of that page will be proficient in using `git` to clone it.)

I'm open for better ways to preserve both ways of selecting (entire word or entire block), but I'd rather give up on the single-word selection, because you can always still use simple dragging. But if we can accommodate both needs, even better.
