### ISSUE TITLE
Mass convert all existing content

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej.github.io#11]
The conversion process involves preprocessing each MediaWiki page, converting it with pandoc, and then postprocessing the result. As of this writing the logic lives in `convert/ij_mw_preprocess.py`. It is under active development. We need to iteratively convert the codebase, find problems, tweak the conversion script to fix the problems, and [repeat until all fixed](https://www.youtube.com/watch?v=yo3uxqwTxk0). 😄  For each iteration, the converted pages should be committed to this repository (at least for now), so that progress is publicly visible as the quality of the converted content improves.

**Comment by frauzufall** [comment]
I made first progress with the mass conversion script. This is what it currently does:
- it deletes all `.md` files in `/pages` where line 2 looks like this: `autogenerated: true`
- it starts with a specific page (currently `Development.md`) and converts this page
- it adds `autogenerated: true` to the front matter
- it collects all internal links and converts them in the same fashion iteratively

I'm doing this iterative approach to only convert pages which are accessible from the "core" pages. Maybe that filters out e.g. extension pages.

The links on the pages will not work because the new links are e.g. `/pages/Development` instead of `/Development`. Not sure how we fix this best.

You need to install [markdown-link-extractor](https://pypi.org/project/markdown-link-extractor/) for the script to run.

I uploaded the latest script version and all the converted files. I would be available to chat later (same time as yesterday) @elevans if you want to discuss next steps!

**Comment by frauzufall** [comment]
@elevans @turekg Current progress:
- I fixed the conversion scripts to actually use `process_file` method from @elevans (I removed that call earlier by accident)
- this triggered the conversion of all templates in the wikimedia files
- I added all missing includes for the templates (only dummies for now)
- I blacklisted pages failing in pandoc or producing liquid syntax errors in `mass_convert.py`
- I blacklisted placeholder includes which procude liquid syntax errors in `ij_mw_preprocess.py`
- the youtube widget gets parsed, the others replaced for now since they were producing liquid syntax errors
- if the mediawiki pages contain templates inside of templates, they are parsed now too

My next steps:
- figure out why the markdown is sometimes not rendered
- parse the template parameters in the mediawiki files and hand them over to the includes
- I would probably move on to have a look at the image files next then
- make a file keeping track of converted vs unconverted files

More questions:
- we need to figure out what all these new templates were supposed to do originally - does someone know where the original template code lives? Can we access it?
- I am still only recursively converting the pages coming from the top navbar. We need a more concrete plan for how to separate extension files and how to make all the URLs work

Right now there are still some obvious conversion issues to solve and then maybe @turekg can scan the pages and collect more TODOs :)

**Comment by frauzufall** [comment]
Today's progress:
- discussed strategies with @elevans, found template files (`Template:XXX.mw`)
- fixed bugs in the markdown rendering
- `mass_convert`: catch image links, copy images into `images/pages` and fix image links (partly working, e.g. [on this page](https://imagej.github.io/pages/Development))
- `logo` template written as `include` (e.g. used [here](https://imagej.github.io/pages/SciJava.html))

**Comment by frauzufall** [comment]
Today's progress:
- converted `github` and `person` template as `include`
- made example pages for includes ([logo](https://imagej.github.io/pages/demo-logo), [github](https://imagej.github.io/pages/demo-github), [person](https://imagej.github.io/pages/demo-person))
- ran conversion on all `.mw` files and their image media data
- added dummies for missing includes
- fixed the includes to not break the layout all the time
- made statistics, you can access them [here](https://github.com/imagej/imagej.github.io/tree/master/convert/status) (@turekg :) )
  - includes lists for processed pages and media, missing pages and media (based on existing links), unused pages and media
  - `blacklisted_pages` is hand-written, the rest is generated
  - in `template_count` is a list indicating how often a template is used - good news is that we already made the ones with the highest count - this might help to decide where to continue @elevans 

@elevans made a google doc for the template conversion:

**Comment by ctrueden** [comment]
We are finishing doing mass conversions. Future work can all be done in place.
