### ISSUE TITLE
Search results need match-length weighting

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej.github.io#121]
The search results should prefer pages with shorter lengths, or take a penalty for each character that doesn't match the search string.

For example:

The page simply titled `TrackMate` should be the first hit here:
![image](https://user-images.githubusercontent.com/1123809/119842267-264b3180-becc-11eb-8195-fdd16435927d.png)

Same for `Fiji`:
![image](https://user-images.githubusercontent.com/1123809/119842412-43800000-becc-11eb-88d0-7a4781f10c69.png)

**Comment by ctrueden** [comment]
* [typesense docs for the indexer](https://typesense.org/docs/0.19.0/api/documents.html#import-documents)
* [typesense docs for searching from clients](https://typesense.org/docs/0.19.0/api/documents.html#search)
* The ImageJ search uses the [typesense-instantsearch-adapter.js](https://github.com/typesense/typesense-instantsearch-adapter#with-instantsearchjs), plain version.
* It is possible to [customize the widget to filter the results using a transform](https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/query-suggestions/js/)

So ways forward might be:
* Change how we index the content
* Change the search API call we use for retrieving the content
* Postprocess the results in way along the lines of what's discussed above

**Comment by ctrueden** [comment]
I opted for option 3, "Postprocess the results in way along the lines of what's discussed above". For now it just sorts each page of results by its edit distance to the query string. @hinerm Feel free to implement something fancier if you wish.

**Comment by hinerm** [comment]
@ctrueden it's not quite clear to me how search is working.. for example, here's the result for `fij`:

![image](https://user-images.githubusercontent.com/1123809/123272936-d447fc80-d4c7-11eb-8026-4dfafd258461.png)

oddly the `Fiji` site doesn't pop up until I expand the search string to `fiji`

![image](https://user-images.githubusercontent.com/1123809/123273063-ede94400-d4c7-11eb-92e5-2d96b7f404e1.png)

Some times the results are just confusing, like if I search for `ij` why would it match `Virtual` above, say `fiji`:
![image](https://user-images.githubusercontent.com/1123809/123273854-9bf4ee00-d4c8-11eb-99f5-c29f5d8f89bd.png)

I don't think this is something we should devote time to manually tuning.. but maybe there's another off-the-shelf option?

**Comment by ctrueden** [comment]
I think the search is amazingly better than anything we have ever had, and I think it's not worth our time to prototype anything else. But if you really want to, you could try [Meilisearch](https://www.meilisearch.com/). [Here is a comparison chart](https://typesense.org/typesense-vs-algolia-vs-elasticsearch-vs-meilisearch/) of the most popular search systems.

I am also personally satisfied with 0b20222fd45e7c1be47dfc0bf3eb32ac3b778c35, because it makes it so that when you type the complete word (e.g. "fiji" or "trackmate"), then that's the page that comes up on top, as it should. It's true that word fragments, and in particular fragments that do not correspond to the start of words, do not always come up first, because sometimes they aren't in the top 10 results. One way to mitigate that would be to increase the results-per-page to 20 or 25, increasing the likelihood that such pages are in the first batch, and then get sorted to the top by the transform function.

The other thing you could do is post on [their issue tracker](https://github.com/typesense/typesense/issues/) and/or StackOverflow, to get help from people who know this system. I'd definitely recommend we do that before trying to switch to a whole new search infrastructure.

**Comment by ctrueden** [comment]
With 37eea264f73363e82f7de8531cda91112ce1b63b, I made the following improvements:
    
* Increase results per page from 10 to 16.
* Penalize inexact/fuzzy keyword matches below exact ones, and non-beginning-of-word fragment matches below beginning-of-word ones.
* Adjust the layout so it fits at the same height as before (so that mobile search does not go off the bottom of the screen on common phone screen dimensions).
* Make the layout less crappy at narrow/mobile widths.
* Improve vertical alignment of search result rows.

Now, searching for `ij` displays "IJ Blob" as the first match, and all matches whose titles do not include `ij` in them are sorted below those that do.

With 685ce71b39dc13418ccdec013372f315d772e006, the results sorting is now case-insensitive.

**Comment by imagejan** [comment]
I like the search results very much now. I think it would be nice if the URL slug of the page would also be searched (in particular for user pages where you might want to search for the github handle, e.g. `ctrueden` or `imagejan`, but also for other pages maybe, if you only remember part of the URL that you read somewhere, but it doesn't fit the page title verbatim).
