### ISSUE TITLE
Handle missing page descriptions in search

### ISSUE THREAD

**Issue by frauzufall** [imagej/imagej.github.io#22]
We don't have descriptions for the pages converted to mediawiki. We should remove the dummy text there and Just grab the beginning of the text of the page and display it in the search.

**Comment by elevans** [comment]
I agree, we can pop something in the script that'll grab the first couple of lines of the first paragraph.

**Comment by ctrueden** [comment]
I solved this on the server/indexing side, by generating page descriptions from the first sentence of page content, in the case of `description` front matter not being present (d5915b52a13a9c6cc38ca0ec5d854a00f2d5781f). And I removed all the "test description" placeholders (5d0ce170cc0ba3637c10919fea70bd33a9e7e608). So I'd call this issue is resolved!
