### ISSUE TITLE
No more MediaWiki-based .md files

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej.github.io#25]
This means:

* [ ] All Templates and Widgets either converted to includes, inlined or deleted if no longer applicable.
* [x] All pages autoconverted to Markdown, or deleted if no longer applicable.

**Comment by ctrueden** [comment]
Here is a snippet to check which pages are not yet in Jekyll format:
```
for f in *.md; do test "$(head -n1 "$f")" = '---' || echo "[NOT CONVERTED] $f"; done
```

**Comment by frauzufall** [comment]
There are no more MediaWiki-based .md files left. Templates and widgets are not all converted yet, I still deleted the `.md` files, because all `include` files already exist (some are just dummies) and they are not autoconverted. We have to use at the `mediawiki-final` tag for comparing the old templates with the existing includes.

**Comment by ctrueden** [comment]
Thanks @frauzufall, I'm closing this then, since technically it's resolved—even if we do need to finish migrating the remaining templates later.
