### ISSUE TITLE
Consolidate Similar Templates

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej.github.io#35]

**Comment by smgriffin2** [comment]
Citation includes:

Cite
Citation
Publication

**Comment by ctrueden** [comment]
Citation and Publication operated on two different levels, no?

* Citation was a structure for formatting a citation at a higher level. It enables us to e.g. change bibliographic styles of the entire site later easily, should we decide to do so.

* Publication was a big piece of case logic defining known publications, which relied on calling Citation for each.

I do not expect that combining them would be a good idea, since it would result in a ton of copy-paste, and later inconvenience should we want to reformat things, and also potential formatting errors across the various publication citations.

**Comment by smgriffin2** [comment]
Ahh that makes sense. Was wondering why so many arguments in the citation include weren't utilized. Right now, both cite and citation have been rewritten for the new site, and I'll rewrite publication "as is" soon.

It sounds like it may be wise to direct users to use the citation include in order to future-proof the site? I'll add this to my notes to go over once you get back.

**Comment by ctrueden** [comment]
> It sounds like it may be wise to direct users to use the citation include in order to future-proof the site?

Definitely! Documenting the templates front and center, and encouraging people to use them, is a really important cat-herding task. It will reduce the amount of editing-other-people's-stuff-to-use-templates-when-they-didn't we end up doing.

**Comment by smgriffin2** [comment]
Infoboxes:

```
ambox
biginfo-box
info-box
tech-box
warning-box
tip

possibly (these are also infoboxes, but have additional static variable such as image or set text blurb):

imagej1
plugin-removed

```

Figures:

```
figure-center
figure-left
figure-right
```

Images
```
image-center
image-fit
image-left
image-right
```
Sideboxes
```
sidebox-left
sidebox-right
```

Operating systems
```
linux
macos
windows
```

**Comment by ctrueden** [comment]
Progress continues. With f43d95ba3ed39382c37f0bcbc43601daf9d59253, TODO notes about what's left to clean up and consolidate are now in place for all includes in the base `_includes` folder.

**Comment by ctrueden** [comment]
This work was mostly completed. What remains is tracked in #59, #97, and #154.
