### ISSUE TITLE
Markdown preview fine but render failing?

### ISSUE THREAD

**Issue by tferr** [imagej/imagej.github.io#39]
Hi Guys,
I've been looking at the SNT pages, and have a question. Consider, e.g., https://imagej.github.io/SNT__Manual

It renders like this:
![image](https://user-images.githubusercontent.com/2439948/98402878-063e4880-2036-11eb-8843-0acae69dc4a1.png)

So, when I try to edit it (to fix the rendering issues), the page renders the markdown perfectly fine in the Github previewer:

![image](https://user-images.githubusercontent.com/2439948/98403072-5fa67780-2036-11eb-83e0-3417e2543dbc.png)

What is the best way to tackle this: Use a more strict markdown previewer? (Which one?) Use jekyll?

**Comment by ctrueden** [comment]
@tferr Great that you are digging around! :smile:

Certainly the highest fidelity way to test what gets rendered is to install Jekyll locally and use that:

https://imagej.github.io/Editing_the_Wiki#advanced-editing-with-jekyll

GitHub's built-in Markdown preview will never be as good as using Jekyll locally because: A) it doesn't take the Liquid templates into account; and B) we use Jekyll's kramdown Markdown-to-HTML renderer, which might behave differently than GitHub's GFM renderer. We tried using the Jekyll GFM renderer but it had problems, so we're sticking with Kramdown for now.

I believe you can browse any remote site build errors via:

https://github.com/imagej/imagej.github.io/deployments/activity_log?environment=github-pages

But I'm not totally sure... it looks like all the recent deployments were successful, so the log won't help much. To troubleshoot build errors locally, what I usually do is the classic "binary code search" method of:

1. Remove half the page content
2. Check whether it renders correctly
    * If so, replace half of the removed content (so you're sitting at 75% of the original content)
    * If not, remove half of the remaining content (so you're sitting at 25% of the original content)
3. Repeat this process until you've narrowed down which part(s) of the markup are creating problems.

Happy to help further if you are stuck; just let us know.

**Comment by tferr** [comment]
OK. will do. And thanks for the pointers @ctrueden !!
BTW, if one wants to future proof documentation URLs (e.g., https://imagej.github.io/SNT vs https://imagej.net/SNT): Should we start using the former? Or ultimately they will all point to the same place?

**Comment by ctrueden** [comment]
The goal is to update imagej.net to serve the imagej.github.io content by year's end. I will update the static imagej.net banner to clarify this.

As far as future-proofing the URLs: my plan is to update all the links to eliminate the MediaWiki case-sensitivity, in favor of more standard all-small-case-with-dashes URLs. I will of course install 301 redirects for all old links to their new names. (The imagej.net domain will continue to point to one of LOCI's web servers, which will use a Proxy/ReverseProxy to serve the imagej.github.io content... this is how we handle fiji.sc already and it works well, and allows us to be more flexible in exactly how various `fiji.sc/<subdirs>` are handled.

**Comment by ctrueden** [comment]
Just an update on the future-proof URLs: the SNT links became `/plugins/snt` and subpages e.g. `/plugins/snt/modeling`. I hope that's OK. All plugins are going to be documented in `/plugins`, and for plugins wanting more than one page such as SNT, they can have as many as they need in a subfolder so named.

About cutting over imagej.net to the new content: we now have a project board showing the progress:
    https://github.com/imagej/imagej.github.io/projects/2

I'm still naively targeting April 30 to cut over, but looking at the board, it may need to be pushed back a little farther... will depend on how quickly we can make progress. The team (me, @smgriffin2, @elevans, and @hinerm) are all meeting about it weekly on Wednesdays, and it's a top priority for all of us. So it's moving.

Related notes:
* Issue #53 might be of interest to you, since it's about styling a mini-topbar NAV like SNT has in a general way that could be reused by other site sections via an include.
* I did a bunch of work cleaning up the ImageJ guide prototype you did during the 2015 hackathon. That content is now at `/guide` here. Maybe it'll all get thrown out and reconverted from the existing guide, I don't know, but just wanted to give you a heads up. It might finally be in the cards to pursue a conversion+update of the guide to this site, although we'd still need to do a cost-benefit analysis regarding whether having all the content in Jekyll/Markdown meets all the guide's requirements (e.g. PDF generation). Given how powerful Jekyll is, it might, but not sure yet. Happy to discuss further if you have time and interest—or if you're too busy these days, I totally understand, and we may still pursue it at LOCI at some point in the future regardless.

**Comment by ctrueden** [comment]
I'm going to close this issue now, since I don't _think_ there are any actions to take in response to it. As I said above, to get a completely accurate preview, unfortunately one must run Jekyll locally. But at least the GitHub-side preview is relatively decent for previewing basic changes. Happy to reopen this if there is anything concrete we can do to make the process easier for people.
