### ISSUE TITLE
Add user table for Fijiyama plugin #40

### ISSUE THREAD

**Issue by Rocsg** [imagej/imagej.github.io#41]
Hello,
I submitted a pull request on November. It is about updating my plugin page. As I need to make a new page for a new plugin, I would like to know if anything go wrong, or if I can make something else to help.

Nice week  to you all !

**Comment by ctrueden** [comment]
Sorry for the long silence, @Rocsg. Looks like @smgriffin2 merged your PR back in February. Since then, I've cleaned up the Fijiyama page some, including the user table you added with that PR. Reading over the page now, it looks like there are still some styling issues remaining from the migration. Next week is the first "virtual Fiji hackathon" coding sprint, and we're planning to announce next week's topic as a community push to finish cleaning up all the content, so we can finally launch the new website. I expect the Fijiyama page to be fixed up as part of that. Anyway, I think this issue can be closed, right? If not, please reopen with details of what else needs to be done. Thanks!

**Comment by Rocsg** [comment]
Ok for me. Nice !
I keep following the hackathon objectives. I am not fluent in web page
designs and a lot of other competencies that you need, but I'll check if I
can help in a way or another.

See you !

Romain Fernandez
Researcher in computer sciences
CIRAD, France


Le mer. 26 mai 2021 à 15:28, Curtis Rueden ***@***.***> a
écrit :
