### ISSUE TITLE
Logo link should go to ImageJ2 (Home, about...) - NOT fiji

### ISSUE THREAD

**Issue by etarena** [imagej/imagej.github.io#5]

**Comment by ctrueden** [comment]
The `MediaWiki::MainPage` is set to `Fiji`. And `MediaWiki::Mainpage-ij2` is set to `ImageJ2` with case logic in the `LocalSettings.php` to override it. But this is currently broken and `imagej.net`/`wiki.imagej.net` still use `Fiji` instead of `ImageJ2`.

Ultimately, we want to eliminate the hostname case logic in `LocalSettings.php` to always act like `imagej.net` and set `fiji.sc/[0-9A-Z]*` to redirect to `imagej.net` (with `http://fiji.sc/` toplevel redirecting to `http://imagej.net/Fiji`). So then there will only be _one_ URL for the content.

**Comment by ctrueden** [comment]
The `imagej.github.io` base page now redirects to `imagej.net`, which redirects to `imagej.net/Welcome`.
