### ISSUE TITLE
Generalize styling of related plugins (ex: SNT)

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej.github.io#53]
The [SNT](https://imagej.github.io/plugins/snt/) page has an intro box with links to related sections. This should be standardized, perhaps through front matter?

**Comment by elevans** [comment]
I'm on this one now!

- [] test a front matter SNT menu solution (should be generic)
- [] make it look pretty

**Comment by ctrueden** [comment]
@elevans As discussed in chat, here's what I'd like to see: write an include called `section-menu` that loops over site.pages, filtering to only pages in the _current page's folder_. So for example, in `_pages/plugins/snt/index.md`, assuming `{% include section-menu %}` is written at the top and/or bottom of the file, it would create a horizontal nav bar with links to each page of that folder, with `index` first and I suppose then the rest in alphabetical/sorted order by title.

Please let @hinerm and/or I know if you need any help with it! I think it will be super slick if we can pull it off. :smile:

**Comment by ctrueden** [comment]
I have now implemented a built-in horizontal nav bar. You simply add `nav-bar: true` in the front matter of any page where you want to have such a thing. It will include links to all other pages in that page's folder.

It still needs to be styled better. As of this writing, it is very basic, and does not match the sidebar floating gray boxes. Maybe it should be a floating gray box as well? And maybe it should be sticky as well, so that when you scroll down, it doesn't disappear. That way, pages like SNT wouldn't feel the need to include a second copy of it at the bottom of each page.

For control freaks, you can alternately something like:
```
nav-bar:
- title: Greetings
  url: hello
- title: See You Later
  url: goodbye
```
to explicitly enumerate all the links. But of course this is much more verbose and must be copy-pasted to all pages in the section. So I think it's nicest if we make the true behavior as pleasing as possible for folks.

**Comment by ctrueden** [comment]
With c4d38bdb7bc8ccfac2a404fd37c761a1ef2cb77f and 5a81d3687e426292893c0acbedb3de584581a99f, this issue is now fully resolved.
