### ISSUE TITLE
Restore project icon near page title

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej.github.io#97]
The [project include](https://github.com/imagej/imagej.github.io/blob/main/_includes/project) has incorrect logo links. Even when the links are corrected though it doesn't render correctly. It is supposed to create a little shadow box with an icon:

![image](https://user-images.githubusercontent.com/1123809/117482212-ab74a380-af29-11eb-824d-8deec9f0245c.png)

But I don't think there is a corresponding place for it in the current layout - it would compete with the dockable sidebars now. Instead of trying to fiddle with fixing it I suggest just removing it in favor of https://github.com/imagej/imagej.github.io/issues/53.

**Comment by hinerm** [comment]
@ctrueden any objections?

**Comment by ctrueden** [comment]
This feature came about with substantial effort on my part in response to criticism from the various involved groups about the merger of the ImageJ and Fiji wikis. The end result (on the MediaWiki) made all involved parties happy, so we need to roll it forward to the new site in some similar form: the `project` metadata is necessary to delineate site sections, whether they related to ImageJ1, ImageJ2, Fiji, ImgLib2, SCIFIO, etc. It needs to be reflected in some very noticeable way on project-specific pages, with a tooltip on mouseover explaining the project in a sentence or two, and a hyperlink to the wiki's main page about that project. You may be right that it can all be tackled as part of #53. But I'd favor keeping this open as its own issue, since the concern here is slightly different than #53: this issue can be about clearly identifying which project each page is part of, whereas #53 is more about unifying navigation when a site section wants to have its own extra "mini-menu". What do you think?

**Comment by hinerm** [comment]
@ctrueden sure, we could add another sticky side panel, maybe that defaults top right, and if there is a `project:` in the front matter it gets an icon and link?
